Graeme's ItsyBitsy M4 CircuitPython Fork (#1)
* Additional cast through void*

Tell the compiler we know what we are doing, and that the bytes are
correctly aligned, to avoid compiler warning:

error: cast increases required alignment of target type

* Enable native code emitter

Involved disabling animated GIF (I'll cope) and BLE (which is maybe more
useful, though not right now as no BLE hardware)

* Enable native extension modules

* Remove space

* Same useful changes for Grand Central

* the note is in its attack phase

---------

Co-authored-by: Jeff Epler <jepler@gmail.com>
Co-authored-by: Dan Halbert <halbert@adafruit.com>